export const FIND_CAKE_PAGABLE_REQUEST = 'FIND_CAKE_PAGABLE_REQUEST';
export const FIND_CAKE_PAGABLE_SUCCESS = 'FIND_CAKE_PAGABLE_SUCCESS';
export const FIND_CAKE_PAGABLE_FAILURE = 'FIND_CAKE_PAGABLE_FAILURE';

export const FIND_CAKES_REQUEST = 'FIND_CAKES_REQUEST';
export const FIND_CAKES_SUCCESS = 'FIND_CAKES_SUCCESS';
export const FIND_CAKES_FAILURE = 'FIND_CAKES_FAILURE';

export const FIND_CAKES_BY_CATEGORY_REQUEST = 'FIND_CAKES_BY_CATEGORY_REQUEST';
export const FIND_CAKES_BY_CATEGORY_SUCCESS = 'FIND_CAKES_BY_CATEGORY_SUCCESS';
export const FIND_CAKES_BY_CATEGORY_FAILURE = 'FIND_CAKES_BY_CATEGORY_FAILURE';

export const FIND_CAKE_BY_ID_REQUEST = 'FIND_CAKE_BY_ID_REQUEST';
export const FIND_CAKE_BY_ID_SUCCESS = 'FIND_CAKE_BY_ID_SUCCESS';
export const FIND_CAKE_BY_ID_FAILURE = 'FIND_CAKE_BY_ID_FAILURE';

export const ADD_ITEM_TO_CART_REQUEST = 'ADD_ITEM_TO_CART_REQUEST';
export const ADD_ITEM_TO_CART_SUCCESS = 'ADD_ITEM_TO_CART_SUCCESS';
export const ADD_ITEM_TO_CART_FAILURE = 'ADD_ITEM_TO_CART_FAILURE';
