export const FIND_CAKE_PAGABLE_REQUEST = 'FIND_CAKE_PAGABLE_REQUEST';
export const FIND_CAKE_PAGABLE_SUCCESS = 'FIND_CAKE_PAGABLE_SUCCESS';
export const FIND_CAKE_PAGABLE_FAILURE = 'FIND_CAKE_PAGABLE_FAILURE';